services:
  postgres:
    image: postgres:15
    restart: always
    container_name: nitro_postgres
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABSE_USER}
      POSTGRES_PASSWORD: ${DATABSE_PASSWORD}
      POSTGRES_DB: ${DATABSE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
