name: Expo Preview Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --frozen-lockfile


      - name: Install Expo CLI
        run: yarn global add expo-cli

        
      - name: Install EAS CLI
        run: yarn global add eas-cli

      - name: Run EAS Build Preview
        run: eas build --platform=android --non-interactive --profile preview
      - name: Debug token (safe)
        run: echo "Token prefix: ${EXPO_TOKEN:0:5}********"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
